export const objagendamento = {
  id_agendamento: 66,
  id_agenda: 117,
  id_cliente: 32,
  data_realizacao: 1649944800,
  data_agendamento: 1649804646,
  Agenda: {
    id_agenda: 117,
    id_barbeiro: 619331,
    data: 14,
    periodo: 'tarde',
    hr_inicio: 1649948400,
    hr_fim: 1649948400,
    agendado: true,
    minutos_disponiveis: 0,
    Barbeiro: {
      id_barbeiro: 619331,
      id_usuario: 55,
      Usuario: {
        id_usuario: 55,
        nome: 'Renan Marcelo Henrique',
        email: 'renan.enriq96@gmail.com',
        sexo: 'M',
        senha: '$2a$10$4GyohNj0UoNU7Lpt84.Fb.BvKkZPlG7R59f7po2XeDyy/j9Y6bG5m',
        data_nascimento: 886204800,
        telefone: '(19)98836-8576',
        token_senha: null,
        dt_token_senha: null,
      },
    },
  },
  Cliente: {
    id_cliente: 32,
    id_usuario: 94,
    Usuario: {
      id_usuario: 94,
      nome: 'Vicente Augusto Kolinoski Magalhães',
      email: 'vicente.magalhaes@live.com',
      sexo: 'M',
      senha: '$2a$10$4SedxXK5DceBR/xIgvHLZOAL7X.vxCuyhT9FiizUisAVMix8uLJci',
      data_nascimento: 1649721600,
      telefone: '(48)99816-1858',
      token_senha: null,
      dt_token_senha: null,
    },
  },
  ProcedimentoAgendamentos: [
    {
      id_procedimento_agendamento: 107,
      id_procedimento: 3,
      id_agendamento: 66,
      Procedimento: {
        id_procedimento: 3,
        procedimento: 'Sobrancelha',
        valor: 15,
        tempo_medio: 15,
        descricao: 'Ajuste de sobrancelha',
      },
    },
    {
      id_procedimento_agendamento: 106,
      id_procedimento: 2,
      id_agendamento: 66,
      Procedimento: {
        id_procedimento: 2,
        procedimento: 'Corte de barba',
        valor: 15,
        tempo_medio: 15,
        descricao: 'Corte de barba',
      },
    },
    {
      id_procedimento_agendamento: 105,
      id_procedimento: 1,
      id_agendamento: 66,
      Procedimento: {
        id_procedimento: 1,
        procedimento: 'Corte de cabelo',
        valor: 20,
        tempo_medio: 30,
        descricao: 'Corte de cabelo',
      },
    },
  ],
};
